name: Deploy on Maven Central
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Generate new GPG key
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          cat > gen-key-script <<-EOF
          %no-protection
          %transient-key
          Key-Type: RSA
          Key-Length: 2048
          Subkey-Type: RSA
          Subkey-Length: 2048
          Name-Real: Luiz Fernandes de Oliveira
          Name-Email: luizfernandesoliveiraoficial@gmail.com
          Expire-Date: 1d
          EOF
          gpg --batch --gen-key gen-key-script
          echo "GPG_KEY_ID=$(gpg --list-keys --keyid-format LONG | grep pub | awk '{print $2}' | cut -d'/' -f2)" >> $GITHUB_ENV
      - name: Build and publish to Maven Central
        env:
          GPG_KEY_ID: ${{ env.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn clean verify -Dgpg.keyname=$GPG_KEY_ID -Dgpg.passphrase=$GPG_PASSPHRASE
          mvn deploy -P release -Dgpg.executable=gpg --settings .github/maven-settings.xml